version: '3'

services:
  dokuwiki:
    image: mizunashi/dokuwiki:latest
    ports:
        - "8080:80"
    volumes:
        - ".:/var/www/dokuwiki/lib/plugins/mdpage"
    environment:
        #- DEBUG=true
        - DOKUWIKI_LANG=ja
