version: '3'

services:
  dokuwiki:
    image: mizunashi/dokuwiki:latest
    ports:
        - "8080:80"
    volumes:
        - ".:/var/www/dokuwiki/lib/plugins/mdpage"
        - "./assets/sample-page.txt:/var/www/dokuwiki/data/pages/start.txt"
    environment:
        #- DEBUG=true
        - DOKUWIKI_LANG=ja
