version: 2

jobs:
    build:
        docker:
            - image: circleci/php:7.1-node-browsers
        steps:
            - checkout

            - run: sudo composer self-update

            - run: make
            - run: mkdir -p /tmp/artifacts
            - run: cp archive.tar.gz /tmp/artifacts/plugin-package.tar.gz

            - persist_to_workspace:
                root: /tmp/artifacts
                paths:
                    - plugin-package.tar.gz

    test:
        docker:
            - image: circleci/php:7.1-node-browsers
        steps:
            - checkout

            - run: sudo composer self-update

            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.lock" }}
                    # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
                    - composer-v1-
            - run: composer install --no-ansi --no-interaction --prefer-dist
            - save_cache:
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - vendor

            - run: composer test

    deploy:
        docker:
            - image: circleci/golang:1.8
        steps:
            - checkout

            - attach_workspace:
                at: /tmp/artifacts

            - run: go get github.com/tcnksm/ghr

            - run: |
                VERSION="${CIRCLE_TAG}"
                ghr \
                    -t ${GITHUB_TOKEN} \
                    -u ${CIRCLE_PROJECT_USERNAME} \
                    -r ${CIRCLE_PROJECT_REPONAME} \
                    -c ${CIRCLE_SHA1} \
                    -n "Release ${VERSION}" \
                    "${VERSION}" \
                    /tmp/artifacts

            - run: |
                VERSION="${CIRCLE_TAG}"
                git config user.email "release-bot@users.noreply.github.com"
                git config user.name "release-bot"
                git checkout release || git checkout -b release
                cp /tmp/artifacts/plugin-package.tar.gz .
                git add -f plugin-package.tar.gz
                git commit -m "Automatic release v$VERSION"
                git remote add for-release \
                   "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
                git push -u for-release release

workflows:
    version: 2
    test:
        jobs:
            - test
    build-and-deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
                    tags:
                        only: /.*/
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v\d+\.\d+\.\d+$/
